### ISSUE TITLE
customizable or else less personal login icons

### ISSUE THREAD

**Issue by lbestock** [arch-kiosk/arch-kiosk-office#2245] opened 2023-08-24 01:07 UTC
This is a painful ticket for me. I really like the vestiges of the early project, the things that are personal. The yups and nopes. The spider button. The spider button can be turned off and will anyway be the hill I die on in terms of eradicating all personal stuff. It stays. Forever. But the login icons are ready to be rethought. A pharaoh's head and crook and flail only work in part of the world, and since I have sat in a meeting not that long ago when someone vibrated with anger and said he did not feel comfortable in the Joukowsky Institute for Archaeology and the Ancient World because the images of classical art on the walls made him feel excluded.... Well, I want him to use Kiosk. The icons might make him feel excluded.

I also don't want my Tut mask to go away. Can we even imagine having options there? Like New World people can have Olmec heads or Easter Island moai? Although that is potentially offensive to someone too and no longer personal anyway, so maybe something more generic is wanted. How boring and dumb.

**Comment by lbestock** [comment] 2023-08-24 01:23
Look, there is totally a moai icon:
![image](https://github.com/arch-kiosk/arch-kiosk-office/assets/49291909/2440fd1a-cb8e-47ac-96f0-6b05170338c1)

**Comment by lbestock** [comment] 2023-08-24 01:25
Many. 
![image](https://github.com/arch-kiosk/arch-kiosk-office/assets/49291909/493d683e-9c4b-46c7-8980-097a17353db7)
And Olmec heads. Don't know how I feel about the world.
![image](https://github.com/arch-kiosk/arch-kiosk-office/assets/49291909/cab31800-b914-4a8f-b717-c5b638a1a895)

**Comment by urapadmin** [comment] 2023-08-24 08:15
they are all nice but you need to have the rights to publish them (something you just did) ! Do you?

**Comment by urapadmin** [comment] 2023-08-24 09:06
To achieve something like this:
![image](https://github.com/arch-kiosk/arch-kiosk-office/assets/38838314/6ad3f702-d668-4a14-b296-59aadcfb3bef)
and this:
![image](https://github.com/arch-kiosk/arch-kiosk-office/assets/38838314/6e0d3657-52f0-49d4-aae2-fded19b6862c)
all that is necessary is having two custom images, of course, and this customization file:
```
:root
  --header-logo-img: url('/custom_file/images/mkap_logo_small.png')
  --current-user-svg: url('/custom_file/images/user.png')
  --user-password-svg: url('/custom_file/images/pwd.png')

And the rights to use the images.
```

**Comment by urapadmin** [comment] 2023-08-24 09:07
so, we are not exaggerating when we say that Kiosk itself was designed towards customization from the start

**Comment by urapadmin** [comment] 2023-08-24 09:09
some documentation of Kiosk customization would be nice one day, but man, that'll be a task

**Comment by urapadmin** [comment] 2023-08-24 09:10
now you have a task: Please give me two SVGs that we use as the standard svgs. Uronarti will keep its current ones through customization.

**Comment by lbestock** [comment] 2023-08-24 11:10
Wie cool ist das, bitte?
Our software is so rad. But this is totally unfair, I can't find/make icons and get ready for the cleaners at the same time.

**Comment by urapadmin** [comment] 2023-08-24 11:24
can we cut the youth speak?

**Comment by urapadmin** [comment] 2023-08-24 11:31
> Wie cool ist das, bitte? Our software is so rad. But this is totally unfair, I can't find/make icons and get ready for the cleaners at the same time.

you don't have to do it right away. In general I am thinking about getting away from the copyright issue by designing our own icons. You guys have the skills, just perhaps not the time. That is something where (RISD) students could help, if they were in the least helpful. But as for the user-id and password icon, just do it when you have time to make one (don't find one! That runs into the copyright issues even if the images is open source because that often comes with the obligation to cite the creator somewhere)

**Comment by lbestock** [comment] 2023-08-24 22:59
Oh but who could resist? Not me. Your first two are perhaps still too far from PC but pick up on familiar themes. Maybe we should have a whole range? 
![image](https://github.com/arch-kiosk/arch-kiosk-office/assets/49291909/d27d68f1-bc44-46ca-8179-513a46b2c72c)
![image](https://github.com/arch-kiosk/arch-kiosk-office/assets/49291909/9b339904-1f14-4ca1-98cd-60ac4e3e81dd)

**Comment by lbestock** [comment] 2023-08-24 23:00
Hm I like the Ark of the Covenant better a little heavier I think.

![image](https://github.com/arch-kiosk/arch-kiosk-office/assets/49291909/b7368089-4ffb-485f-a1fa-4ed717aba5dd)

**Comment by lbestock** [comment] 2023-08-25 01:01
Needs line weight help.
![image](https://github.com/arch-kiosk/arch-kiosk-office/assets/49291909/1f640143-2a94-4e51-b105-71bce356d1e8)

**Comment by urapadmin** [comment] 2023-08-25 17:17
> Oh but who could resist? Not me. Your first two are perhaps still too far from PC but pick up on familiar themes. Maybe we should have a whole range? ![image](https://user-images.githubusercontent.com/49291909/263123866-d27d68f1-bc44-46ca-8179-513a46b2c72c.png) ![image](https://user-images.githubusercontent.com/49291909/263123882-9b339904-1f14-4ca1-98cd-60ac4e3e81dd.png)

While the cowboy hat (I suspect it is meant to be an Indy hat) might work to symbolize a user (an indeed how is that PC), the Ark of the Conventant (whatever that is) surely does not symbolize a password universally. Also you must think about the size on the screen. 

What about something simpler for our default (why would we need a whole range unless we have a specific project wanting something specific?). Like a person and a key?

Oh, and please don't use GitHub as the place for the files. We have the google drive for that: \Kiosk Shared Files\material_for_development\images.

**Comment by lbestock** [comment] 2023-08-27 15:27
Super boring, but I guess you are right. Well, you have handcrafted boring boring person and key SVGs in the images folder.

**Comment by urapadmin** [comment] 2023-11-16 20:44
okay, tried to use this after all. Can't. First: That's one file and not two files. Second: It is not an SVG. It only masks as an SVG. So I have no idea where you got those from, but they are bitmaps in an SVG frame.

**Comment by lbestock** [comment] 2023-11-16 22:43
I made them in Illustrator myself. Hmpf.

**Comment by lbestock** [comment] 2023-11-16 22:48
When I save them separately in Illustrator it gives me an SVG code button even. I don't know how else to do this - this is precisely what I did with all the spiders we use. There are at least now two files. I originally made the images as vectors in Illustrator and that is still definitely how I see them. Is it possible googledrive does something malign to them?

**Comment by urapadmin** [comment] 2023-11-16 22:56
and now they are real svgs. You can see that easily:
![image](https://github.com/arch-kiosk/arch-kiosk-office/assets/38838314/51ce0e42-a46a-43ed-af59-98b0449fa299)
The combined ones are waaaaaay larger.

**Comment by urapadmin** [comment] 2024-02-03 17:41
### Kiosk 1.5.23
- the defaults are now set to boring but politically less difficult

**Comment by luizaogs** [comment] 2024-02-05 16:49
This hasn't been released, right? Just making sure I'm not confused by the numbers again.

**Comment by urapadmin** [comment] 2024-02-05 17:05
No, I only released the plugin yesterday. But I need to release it because now PVD has not login icons anymore.

**Comment by luizaogs** [comment] 2024-02-05 18:05
MKAP too, it seems.

**Comment by urapadmin** [comment] 2024-02-05 21:56
### Kiosk 1.5.23.1
- now the login icons should show our new boring but politically correct default

**Comment by lbestock** [comment] 2024-02-05 23:48
PVD now boring.
But BUAP now misses its pharaoh head (still has the crook and flail).

**Comment by lbestock** [comment] 2024-02-05 23:49
And URAP has the pharaoh head but the password is the boring one instead of the crook and flail.

**Comment by luizaogs** [comment] 2024-02-05 23:51
MKAP appears to only have a password icon (the key) currently.

**Comment by luizaogs** [comment] 2024-02-05 23:52
I guess the question is where this has been released? Should we check all kiosks?

**Comment by urapadmin** [comment] 2024-02-06 00:23
> PVD now boring. But BUAP now misses its pharaoh head (still has the crook and flail).

BUAP? I have not rolled BUAP out, have I?

**Comment by urapadmin** [comment] 2024-02-06 00:26
I have released MKAP, URAP, PASU and PVD, I think. It will roll out to all projects bit by bit and then we have to apply whatever icon a project actually wants. I will make sure in the next iteration that all Egypt projects have the pharaoh and crook and flail. 
Customization was a bit of a mess here (because it was not really necessary before). Seems I have to be a bit more systematic about it.

**Comment by luizaogs** [comment] 2024-02-06 00:30
PASU looks correct.

**Comment by urapadmin** [comment] 2024-02-06 17:40
Now systematically:
Each of these needs to be installed and then the new clone/update custom config script executed with the result that the projects in Egypt have Pharaoh and Flail and the others the neutral icons.

- [ ] PVD
- [ ] MKAP
- [ ] URAP
- [ ] MADP
- [ ] KAMBE
- [ ] KHPP
- [ ] PASU
- [ ] PACHA
- [ ] USTP
- [ ] ARCH1900
- [ ] BUAP

**Comment by urapadmin** [comment] 2024-02-06 22:14
### 06.II.24 17:00
All projects should be ready now. To achieve this I also had to update them to Kiosk version 1.5.23.1

**Comment by urapadmin** [comment] 2024-02-06 22:32
paaaaaaaaaaaaaainful. I hope this is done now.

**Comment by urapadmin** [comment] 2024-02-06 22:33
I just close this. It will show soon enough if there are icons missing.

**Closed by urapadmin** 2024-02-06 22:33 UTC
Labels: kiosk, user manual
