### ISSUE TITLE
Please wait window appears and does not go away

### ISSUE THREAD

**Issue by luizaogs** [arch-kiosk/arch-kiosk-office#1925] opened 2022-11-13 00:11 UTC
13.7.5

This happened after I added a bunch of new cm. First the back arrow disappeared on the cm layout, so I used the burger menu to go back to start. I then tried going back to unit LA but when I got there I got a please wait …. screen that wouldn’t go away. I tried to navigate elsewhere but navigation was not working either, and clicking on different entities there merely highlighted them (see screenshot below)

![B56528FE-A137-4037-B898-3E1FBBB78B7A](https://user-images.githubusercontent.com/67970402/201499622-47940956-bad8-4cbc-b8e5-16c936f5d1f6.png)

**Comment by luizaogs** [comment] 2022-11-13 00:14
add_cm_photo_to_cache: single image with param OnObjectModify, $$cache_done=0
add_cm_to_cache: image missing: 0/1
is_cache_update_needed: image is there in OnObjectModify but record is not-> DONT process cache
add_cm_photo_to_cache: doing nothing.
image_validate: field img
image_validate: going to hidden
add_cm_photo_to_cache: single image with param , $$cache_done=0
add_cm_to_cache: image missing: 0/0
is_cache_update_needed: OnValidate but NOT CACHE_DONE-> process cache
add_cm_photo_to_cache (deferred): cache update needed.
execute_deferred_cache_operation: call with param delay
execute_deferred_cache_operation: calling myself with a delay of ,5 seconds
add_cm_photo_to_cache: single image with param description_only, $$cache_done=0
add_cm_to_cache: image missing: 0/0
is_cache_update_needed: OnValidate but NOT CACHE_DONE-> process cache
add_cm_photo_to_cache (deferred): cache update needed.
execute_deferred_cache_operation: call with param delay
execute_deferred_cache_operation: calling myself with a delay of ,5 seconds
save_image: enter for img
save_image: saving image data for field
save_image: enter for img
save_image: saving image data for field
switch_off_menu: Switched the menu off. isMasterDb = nope
switch_off_menu: Switched the menu off. isMasterDb = nope
switch_off_menu: Switched the menu off. isMasterDb = nope
switch_off_menu: Switched the menu off. isMasterDb = nope

**Comment by luizaogs** [comment] 2022-11-13 00:14
Test log above.

**Comment by luizaogs** [comment] 2022-11-13 00:15
Going back to the start page and then back to LA does not resolve it. Clicking out of FM and going to another also does not.  Things only go back to normal once I log out and close FM, and log back in again.

**Comment by luizaogs** [comment] 2022-11-13 00:17
Related to #1808 ?

**Comment by urapadmin** [comment] 2022-11-13 11:39
yes, this is basically the same just happening in a different layout. 
It is correct (as in "I know why"), that the please wait does not go away until you leave filemaker. 
I would need the log exactly after the insertion that lead to the please wait pane not going away again. Is that log from that moment?

**Comment by urapadmin** [comment] 2022-11-13 11:41
I would also want to know if the image actually got inserted AND if the file identifier cache was populated correctly for the image (I know, it's been a while since you had to check that. Can you remember?)

**Comment by urapadmin** [comment] 2022-11-13 11:43
and then I must ask: Can you provoke it?

**Comment by urapadmin** [comment] 2022-11-13 12:10
- [ ] one thing I definitely need to do is make the please wait go away on next navigation. 
- [ ] perhaps I should also allow to close it with some kind of button that one cannot click accidentally

**Comment by luizaogs** [comment] 2022-11-13 12:28
> yes, this is basically the same just happening in a different layout. It is correct (as in "I know why"), that the please wait does not go away until you leave filemaker. I would need the log exactly after the insertion that lead to the please wait pane not going away again. Is that log from that moment?

No, but I am not sure if the please wait was triggered by the insertion? I guess so. But I only got it once I left the cm layout (where the insertion was done) and got back into the unit layout by going back to the start page. The insertion seems to have triggered the missing back button - I guess that is connected to the please wait panel?

**Comment by luizaogs** [comment] 2022-11-13 12:29
> I would also want to know if the image actually got inserted AND if the file identifier cache was populated correctly for the image (I know, it's been a while since you had to check that. Can you remember?)

The image was inserted. Let me see about the file identifier cache .... but is that something I can check now, or would it have to be done right when the image was inserted?

**Comment by luizaogs** [comment] 2022-11-13 12:29
> and then I must ask: Can you provoke it?

I'll try :)

**Comment by urapadmin** [comment] 2022-11-13 12:39
you go have breakfast, first! 🍞 🍨

**Comment by urapadmin** [comment] 2022-11-13 12:40
> > I would also want to know if the image actually got inserted AND if the file identifier cache was populated correctly for the image (I know, it's been a while since you had to check that. Can you remember?)
> 
> The image was inserted. Let me see about the file identifier cache .... but is that something I can check now, or would it have to be done right when the image was inserted?

you can (after 🍞 )

**Comment by urapadmin** [comment] 2022-11-13 12:47
> > yes, this is basically the same just happening in a different layout. It is correct (as in "I know why"), that the please wait does not go away until you leave filemaker. I would need the log exactly after the insertion that lead to the please wait pane not going away again. Is that log from that moment?
> 
> No, but I am not sure if the please wait was triggered by the insertion? I guess so. But I only got it once I left the cm layout (where the insertion was done) and got back into the unit layout by going back to the start page. The insertion seems to have triggered the missing back button - I guess that is connected to the please wait panel?

It is hard to imagine what exactly you might have done. The Please Wait pane becomes visible in the process of inserting the image and creating the file identifier cache entries. At the same time the back button vanishes to keep you from leaving within the process. You must have found a way to either interrupt that process or your timing was in a way that didn't go well with filemaker. That's really just a guess. I wish I could actually see it happening. But I don't even ever use an ipad. You guys are my eyes on that front.

**Comment by luizaogs** [comment] 2022-11-13 14:50
> > > I would also want to know if the image actually got inserted AND if the file identifier cache was populated correctly for the image (I know, it's been a while since you had to check that. Can you remember?)
> > 
> > 
> > The image was inserted. Let me see about the file identifier cache .... but is that something I can check now, or would it have to be done right when the image was inserted?
> 
> you can (after 🍞 )

Ok I can't remember :) Help.

**Comment by urapadmin** [comment] 2022-11-13 18:09
basically you just look in the image gallery if all the archaeological contexts are listed for the image you inserted. So for a locus photo image for LA-001 that would be two: LA-001 and LA. For a dayplan image is it just "LA".

**Comment by luizaogs** [comment] 2022-11-13 18:16
Ah. So yes, that all looks fine.

**Comment by urapadmin** [comment] 2022-11-13 18:30
hm. Strange. In that case I doubt that the test log would have revealed anything illuminating. 
All I can do is install a few precautions that make sure that the panel goes away. But that feels like patching over something the cause of which I'd rather understand. 
I have learned to live with that in filemaker.

**Comment by urapadmin** [comment] 2022-11-14 12:28
### recording 13.6.7
- precautions installed. Whenever a navigation happens (back button, navigation histories) a potentially visible please wait panel will be switched off
- the wait panel itself has a little nearly invisible close X in the upper left corner

**Closed** 2022-11-18 12:05 UTC
Labels: bug, filemaker recording
