### ISSUE TITLE
q&v: bug that I can't describe in a title

### ISSUE THREAD

**Issue by luizaogs** [arch-kiosk/arch-kiosk-office#2356] opened 2023-11-05 22:28 UTC
Let's see if I can reproduce it in a coherent way and describe it here: 

Search for PBA.
Click on PBA-004-4.
Use footsteps in cm view to open the PVD site window. Works.
Go back to PBA-004-4 and now use footsteps to open the PBA locus view. Works. 
Now, using the x, close the PBA-004-4 view.
Close the PBA view.
Click on the still open PVD view and you get this: 

<img width="1487" alt="Screenshot 2023-11-05 at 2 26 56 PM" src="https://github.com/arch-kiosk/arch-kiosk-office/assets/67970402/cb05e785-a525-454b-ba80-ecc42cf22631">

So now the PVD view has turned into the cm view, only the labels don't match. Also clicking on PVD doesn't take me to the actual PVD view with the footsteps, but navigation to PBA and PBA-004 still works.

**Comment by urapadmin** [comment] 2023-11-06 00:34
presumably duplicate of #2330

**Closed** 2023-11-08 23:49 UTC
Labels: 🐞 bug, kiosk
