### ISSUE TITLE
Bridge: state not proper even after resetting

### ISSUE THREAD

**Issue by lbestock** [arch-kiosk/arch-kiosk-office#2864] opened 2024-09-25 15:18 UTC
IBASA trying to do an upload and Bridge thinks it's ready to download while the Hub thinks it's in the field. I am anxious to upload these otherwise unsynchronized data and so am doing this just through Chrome, but the problem wants looking into.

Bridge looked happy, was just wrong. I refreshed, and checked the settings, and still.
![image](https://github.com/user-attachments/assets/5506533f-a837-4f0a-a0d6-a23bcd70d860)

Aha and on upload, the file name is wrong. But that's not going to be a problem and is I suspect unrelated.

**Comment by urapadmin** [comment] 2024-09-25 15:51
I see. What I suspect is that the Bridge update was installed automatically and that is when Bridge forgets its own state and loses its internal download. Did you have to type in the user id, password etc again or so?

What you could have tried in this situation is the unsafe mode. There is a button in the settings that puts Bridge into an unsafe mode. And I think that's when you can send a database from FileMaker to Bridge although it is not in state in the field.

**Comment by urapadmin** [comment] 2024-09-25 15:52
I doubt it but it could be useful to look at the log

**Comment by lbestock** [comment] 2024-09-25 15:53
We didn't have to type in anything new - Bridge just opened looking happy as a clam. 

Because I had to run and Alyssa has her data now online and does not need it immediately on the iPad, we agreed to just touch nothing and meet again next week when I should be somewhat less frazzled.

**Comment by urapadmin** [comment] 2024-09-25 16:33
I suspect that Kiosk Bridge will work fine now that the cycle can start all over again. I guess best is you go through a cycle next week and if that works fine, we just forget about it as a hiccup. I have very little hope that I'll find anything substantial now that the evidence has changed unless it happens repeatedly.

**Comment by urapadmin** [comment] 2024-09-26 23:21
if you can't produce the log next week but Bridge is working fine now, please close this

**Comment by urapadmin** [comment] 2024-09-27 04:10
I tried to reproduce the problem that Bridge loses its state. I could not. I downloaded and sent to FileMaker. After that I upgraded Kiosk Bridge from TestFlight. Afterwards the state was totally fine. So my first idea what might have happened is mush. 

Let's hope for some logs.

**Comment by urapadmin** [comment] 2024-10-16 16:13
I close this due to lost logs and because Bridge behaves properly now,

**Closed as completed by urapadmin** 2024-10-16 16:13 UTC
Labels: 🐞 bug, 📞 support-ticket
