### ISSUE TITLE
Kiosk/Recording: Changed Time Zone, Data Disappeared/Inconsistently shown in file repository vs Recording App

### ISSUE THREAD

**Issue by maychu16** [arch-kiosk/arch-kiosk-office#2463] opened 2024-01-09 03:41 UTC
I changed timezone on my laptop since I am traveling and I also changed the timezone of my workstation in the hub to reflect the timezone I am in.
I was working on the usual photo input process: assigning units and loci in the file repository and then working in the recording app for the context. I finished working on the photos and uploaded the files to sync it. Only some data got synced. There are some photos for which I typed in context information but they did not get synced. And then, there are other photos that did get synced and is shown in the file repository and director's view but when I downloaded the workstation again to continue working, they are all empty as if I haven't typed any context information in (although majority of them shows up in file repository).
I am wondering if it is a bug or I didn't change my timezone settings correctly. Please let me know how to proceed. 

Attached photos show that even though the context information are missing in the recording app, they are in fact present in the file repository. 

<img width="1512" alt="Screenshot 2024-01-08 at 9 42 14 PM" src="https://github.com/arch-kiosk/arch-kiosk-office/assets/153842762/951254bc-45dc-45b8-8a9d-ec075bbfb600">

<img width="1512" alt="Screenshot 2024-01-08 at 9 40 35 PM" src="https://github.com/arch-kiosk/arch-kiosk-office/assets/153842762/8a8814ba-b108-4b2c-8ec9-6ec27ae6c539">

**Comment by maychu16** [comment] 2024-01-09 03:56
The photos that I typed in the context info, then did not sync properly (?) are showing up empty in file repository but in query view, they have these weird strings of name. 

<img width="1512" alt="Screenshot 2024-01-08 at 9 54 59 PM" src="https://github.com/arch-kiosk/arch-kiosk-office/assets/153842762/ac818992-25f0-461f-8ee7-5199bbbe8551">

**Comment by urapadmin** [comment] 2024-01-09 15:23
traveling myself, currently, so I am slow to respond. Please don't upload again for right now as that might give me the chance to get the last file you uploaded (it will otherwise be overridden). 

As for the timezones: When exactly did you change your timezone on your computer? After you downloaded or even had worked on some data? Or did you change it before you prepared the workstation and after you changed the GMT setting for your Kiosk dock?

I will have a look at the issue asap.

**Comment by urapadmin** [comment] 2024-01-09 15:42
okay, I have at least secured the files. The last upload yesterday evening at about 10 pm. That's the one that didn't seem to have gotten imported properly, right?

**Comment by maychu16** [comment] 2024-01-09 15:55
Yes, the 10pm file was the last one I uploaded.
I changed the timezone first on my laptop and then I updated the workstation in the hub to GMT-6. That was a few days ago and I didn't work on inputting data for the past few days since I changed the timezone. Last night was the first time I uploaded the file. So, it was changed way before I downloaded a new workstation or worked on it.

**Comment by urapadmin** [comment] 2024-01-09 17:48
okay, I can see the issue of the image descriptions that do show in the file repository but not in the recording app. I don't know why that happened, that needs deeper analysing than I can do on the move. But it can be easily fixed by just renewing your dock.
You have not made any more changes in your current download, right?

**Comment by maychu16** [comment] 2024-01-09 18:15
Is renewing and resetting and downloading the file again the same? Because I tried downloading it twice last night after the first file show empty context descriptions. 
I haven’t made any new changes.

**Comment by urapadmin** [comment] 2024-01-09 18:44
no, renewing is more thorough. But also not really intended to be used lightly (there is something wrong if renewing is necessary). In this case I even have to renew the whole recording group. While resetting your dock is okay, please don't use any of the other options yourself. We should have given you guys more limited privileges so that you would not see those rather exotic options.

I have done that now and you will find the context-dependent image descriptions that DID sync properly in the recording app after downloading your dock again.

Unfortunately I do not see a good way to reliably recover those descriptions you typed in yesterday that DID NOT sync. I am afraid I must ask you to type these in again. 

Why these things happened is not entirely clear to me, but we have a theory. We think it all has to do with a combination of the TimeZone shift West (which makes your changes in the recording app earlier than the server in Providence) and using the file repository to assign the images to archaeological contexts. 

So this is our workaround: After you assigned images to contexts in the file repository, pause for an hour. That compensates for the time zone shift. Only after the hour prepare your dock and make changes in the recording app. To be on the safe side I suggest you make only a few, upload, import, synchronize and download again. If your changes are there, you should be safe and can work on a larger batch in the recording app.

**Comment by urapadmin** [comment] 2024-01-09 18:46
for now I have to shut down the BUAP server anyhow to import the December 2010 photos for you.

**Comment by urapadmin** [comment] 2024-01-09 22:18
@arch-kiosk/buap The BUAP server space is up again. The images for December 2010 are now available in the file repository. Should you be in an earlier time zone than GMT+5, see the above explanations and precautions for the current BUAP workflow.

**Comment by maychu16** [comment] 2024-01-10 05:04
I followed the instructions and waited an hour. It seems to be working properly for now. I am just curious, when Heidi just worked in the recording app and synced, she didn't have any issue. Is this because I am working in the file repository and the recording app at the same time?

**Comment by urapadmin** [comment] 2024-01-10 14:44
yes, that is what we believe. It is the combination of both. But again, I won't have the chance to analyze this more deeply before Friday.

**Comment by urapadmin** [comment] 2024-01-12 03:47
I can confirm now the issue with the description that did not get synced. It is as suspected: assigning an image to a context stamps the relation between record and image with the server's time, so GMT-5. Sending that to a recording app that operates in an earlier timezone (GMT-6) and then changing the record by adding a description stamps the record with the dock's timezone GMT-6. When synchronizing later the modification happened earlier in time than the original image assignment in the master database and hence does not get synchronized. 

This does not explain the phenomenon of the description that got properly synced but the changes did not get transported back to the recording app. That's stays a mystery for now, although it is pretty likely that it has to do with the different time zones as well.

As Kiosk was not designed to operate in different time zones, there is not simple technical solution to this problem. We must stick with the modified workflow until we all are back in the same time zone. But at least we know now that the workaround indeed addresses the issue.

**Comment by urapadmin** [comment] 2024-01-12 03:53
see the very old #293

**Comment by urapadmin** [comment] 2024-01-12 03:55
I close this ticket as the immediate issue is addressed. The rest will have to be tackled one day when starting on #293

**Closed by urapadmin** 2024-01-12 03:55 UTC
Labels: 📞 support-ticket, new-issue
