### ISSUE TITLE
please wait window shows up and doesn't leave in locus form

### ISSUE THREAD

**Issue by luizaogs** [arch-kiosk/arch-kiosk-office#1808] opened 2022-10-08 17:39 UTC
The following occurred when I was trying to create a new collected material. It popped up when I clicked on the collected material tab. Simply exiting out of the FM window and returning to it doesn't solve the problem. Actually exiting FM and coming back works.

![IMG_0307](https://user-images.githubusercontent.com/67970402/194720436-bd0ff836-e1c9-4494-a506-2196b479105a.PNG)

I can't think of anything weird leading up to it. I had added two images to the locus, but that's it.

**Comment by urapadmin** [comment] 2022-10-08 17:50
a pity I can't get my hands on the log of that one. That's at least me controlling that Please wait ...
I do suspect that's a timing issue. 
Where had you been before you clicked on the cm tab?
What does "Exiting out of the FM Window"? mean? iPad's Home button and then back in?

**Comment by luizaogs** [comment] 2022-10-08 17:59
I had been adding images to the locus before clicking on the cm tab. And yes, home button and back in didn't work. Closing the app and going back in worked.

**Comment by urapadmin** [comment] 2022-11-13 11:42
same as #1925 but different layout. It all looks like a timing issue.

**Comment by urapadmin** [comment] 2023-01-02 15:50
- I should at least install the same precautions in loci (and collected material for that matter) as I did in #1925 for the other layouts.
- And then the thing goes into "under observation"

**Comment by urapadmin** [comment] 2023-05-01 23:27
### recording 14.5.x
- The precaution if a X in the upper left corner is in place. So the please wait can be closed if it does not go away itself.
- I move it under observation and you guys hack at the locus form until it reappears in some reproducible or at least describable way

**Comment by luizaogs** [comment] 2023-05-07 19:17
I just poked around in loci a lot and I see please wait all the time but it hasn't frozen again. For the record.

**Comment by urapadmin** [comment] 2023-05-07 21:48
I think of it most likely on projects that have quality control activated. I can't remember, is that the case in PVD? I suspect so.

**Comment by urapadmin** [comment] 2023-05-07 23:09
I think we can close this until somebody gets the issue again,

**Closed by urapadmin** 2023-05-07 23:09 UTC
Labels: 🐞 bug, small

**Comment by luizaogs** [comment] 2023-05-07 23:12
Oops sorry, I was going to check this later - I finally got off my couch and am back out in civilization for dinner with a friend.

**Comment by urapadmin** [comment] 2023-05-07 23:18
that is a very good thing to do!
