### ISSUE TITLE
recording lots: New approach

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#2490] opened 2024-01-19 17:23 UTC
inputting lots just became more complicated:

- some projects use unit-wide lots (BUAP)
- some use locus-wide lots (URAP, KHPP)
- some want their lots auto-generated (usually the field projects, but not legacy input)
- some projects want to allow duplicate lots (legacy) but that should only happen after a warning. 
- most projects don't allow duplicate lots
- lots must be numeric
- lots cannot exceed a certain number (it has always been 100 for locus-wide lots)

This also summarizes
- #2487 
- #2488 
- #2489

**Comment by urapadmin** [comment] 2024-01-19 17:37
### recording 15.13.2
- "lot_auto_generate" still decided whether or not the lot will be auto generated (now according to the "lot_domain", see below). 
- In combination with "lot_input_type" = "auto" it behaves as it has always been: The lot number gets auto generated and that's that. In combination with "lot_input_type" = "free input" it pre-renders the next lot number and suggests it in the input. If auto generation is off the free input only presents a blank input field to begin with.
- "lot_domain" is "locus" by default but can be "unit". This decides if a lot is generated (and checked) within a locus or within a unit
- "lot_max_number" is "100" by default and can be changed to "0" (no check of a max number) or some other number. In the latter case that number cannot be succeeded by either the auto generation or free input. (Exception see "lot_check_type").
- lot_check_type

**Comment by urapadmin** [comment] 2024-01-19 23:30
BUAP needs 
- "lot_auto_generate" set to nope
- "lot_domain" set to "unit"
- "lot_max_number" set to 0 or left empty
- "lot_check_type" set to "warning"

**Comment by urapadmin** [comment] 2024-01-20 00:10
@lbestock: I have already added all the lot config keys that are necessary for BUAP. Nothing to do for you here.

**Comment by luizaogs** [comment] 2024-01-20 16:45
I don't really get the unit generation part. The lot is checked in the unit because the error messages I have gotten (see #2494 ) apply to that unit when I have that in the configuration key, but it still shows up under locus -- with the locus identifier as part of the lot identifier. Is that correct? 

For example, this lot was created with "unit" in lot_domain: 

<img width="1027" alt="Screenshot 2024-01-20 at 8 44 33 AM" src="https://github.com/arch-kiosk/arch-kiosk-office/assets/67970402/0dec717d-e2a2-4655-ac80-c17094773496">

**Comment by luizaogs** [comment] 2024-01-20 16:50
Changing the lot max number to 0 did not work - I was still able to add a lot.

**Comment by urapadmin** [comment] 2024-01-20 17:06
> Changing the lot max number to 0 did not work - I was still able to add a lot.

but that is what is supposed to happen: 0 (or leaving it blank) means there is no check at all.

**Comment by luizaogs** [comment] 2024-01-20 17:07
Ok, sorry. I missed the part where you say 0 means no check.

**Comment by luizaogs** [comment] 2024-01-20 17:09
Well now I set the max number to 9 and it let me add a lot 10, so something seems off.

**Comment by urapadmin** [comment] 2024-01-20 17:40
> I don't really get the unit generation part. The lot is checked in the unit because the error messages I have gotten (see #2494 ) apply to that unit when I have that in the configuration key, but it still shows up under locus -- with the locus identifier as part of the lot identifier. Is that correct?
> 
> For example, this lot was created with "unit" in lot_domain:
> <img alt="Screenshot 2024-01-20 at 8 44 33 AM" width="1027" src="https://private-user-images.githubusercontent.com/67970402/298295749-0dec717d-e2a2-4655-ac80-c17094773496.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU3NzE5NjksIm5iZiI6MTcwNTc3MTY2OSwicGF0aCI6Ii82Nzk3MDQwMi8yOTgyOTU3NDktMGRlYzcxN2QtZTJhMi00NjU1LWFjODAtYzE3MDk0NzczNDk2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIwVDE3Mjc0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdmODFlOWNiZDc5NjY5NWFjNzA5M2M2YTM4ZGNmMGNjZjY3M2MyMTQ2ZjRmYTMzMTIwYTQ3ZmI0MDI3Y2I1ZDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fMK-EjhKd2W4GBEhpEsaVYtAit7qBXqQ1tg_foglvdo">

Independent of #2494:
sounds right, let me paraphrase:
**if you have domain="locus" then** 
- you cannot create the same lot id within the same locus but you can create the same lot id within a unit. 
- if auto_generate is on the suggested next lot id is within the locus, suggesting even a lot that might be used in some other locus.
- the max_limit is independent of the domain, of course, but the error / warning message is not. That's just because the lot might have been generated automatically and if a 101 is generated it makes sense to say "the range of a 100 lots is exhausted for this locus". While if you type in 101 as free input the wording is a bit off and saying "you can't have a lot greater than 100" would suffice. I just did not want to have another case in this out-of-proportion code about lots.
**if you have domain="locus" then** 
- you cannot create the same lot id within the same **unit** and ergo also not within one locus.
- if auto_generate is on the suggested next lot id is within the unit, never creating a lot number that is already being used by another locus of the unit
- max_limit applies the same way as with loci, except that the message now says that the range of lots is exhausted for this "unit" (or whatever a unit is called, sheesh).

**Comment by urapadmin** [comment] 2024-01-20 17:42
and also: Yes, nobody has asked me to show lots under units. Even if all the loci use the same lot list, a single lot still applies to a locus. That's how I understand the archaeology behind it.

**Comment by luizaogs** [comment] 2024-01-20 17:44
> and also: Yes, nobody has asked me to show lots under units. Even if all the loci use the same lot list, a single lot still applies to a locus. That's how I understand the archaeology behind it.

That's right archaeologically, I believe. I was just not understanding the lot - unit relationship in the recording. I'll go through what you outline above in a bit.

**Comment by luizaogs** [comment] 2024-01-20 17:55
Ok now that I understand the unit thing that is working just fine.

**Comment by luizaogs** [comment] 2024-01-20 17:55
> Well now I set the max number to 9 and it let me add a lot 10, so something seems off.

So this is the only issue that is left here.

**Comment by urapadmin** [comment] 2024-01-20 18:01
> > Well now I set the max number to 9 and it let me add a lot 10, so something seems off.
> 
> So this is the only issue that is left here.

what are your exact config keys here, because that one I cannot reproduce anymore

**Comment by luizaogs** [comment] 2024-01-20 18:13
I can't reproduce it either. Maybe one of the new changes you just introduced solved it?

**Comment by luizaogs** [comment] 2024-01-20 18:13
I think this is ok, then.

**Closed by luizaogs** 2024-01-20 18:13 UTC
Labels: A: next!, request, filemaker recording, BUAP
