### ISSUE TITLE
kiosk: users without admin privileges cannot see docks

### ISSUE THREAD

**Issue by lbestock** [arch-kiosk/arch-kiosk-office#1718] opened 2022-06-28 22:11 UTC
Creating new users with less than admin privileges seems to be a problem currently. Kiosk 0.25.6 as seen on the pasu test server, I created two new users, one with admin and one as field-worker. The field-worker sees a totally blank hub, though they can get to the file repository. There are two docks there in default and I expected to be able to see them when logged in as field-worker. I added operator then (though as far as I can see that actually isn't configured for this server) and it made no difference.

**Comment by lbestock** [comment] 2022-06-28 22:14
However, this does NOT happen on the newly updated demo server that is running the same version.

**Comment by urapadmin** [comment] 2022-06-28 22:51
This is quite strange behavior and definitely buggy. I have to examine it closer, my first attempts to prod it have not lead to a clue. So please leave pasu-test alone for now.

**Comment by urapadmin** [comment] 2022-06-29 17:43
### no new kiosk version needed.

Okay, this has to do with a setting "grant_wildcard_access" of the hub. I have changed this for #838 and pasu_test has been our test server then. So this isn't a bug it is expected behaviour on pasu_test (that explains why we see it only there).

I have now set "kiosk\syncmanagerplugin\grant_by_wildcard" to True (the default) and everything should be fine.

**Comment by urapadmin** [comment] 2022-06-29 18:05
### kiosk 0.26.1
I will change this slightly to be really compatible with Kiosk prior to #838: From now on grant_access_to will always return "*" if it is blank. The effect of that is that it cannot be blank (which means I cannot have a workstation that nobody can see except the admin)

And by the way: On Kiosk installations where the issue would cause trouble it always help to add the "prepare workstation" privilege. But I recommend just adding the "*" to all workstations.

**Comment by luizaogs** [comment] 2022-06-30 16:26
This worked in pasu-test just now (logged in as Omar), only there is currently only one workstation showing for me as admin and there were definitely more when I was in there last a few days ago -- have the other ones been deleted or is this some weird side effect of this setting that shouldn't have happened?

**Comment by lbestock** [comment] 2022-06-30 16:33
I deleted them! I think. I was deleting them from both pasu-test and demo in advance of making....a video tutorial (available for viewing, go grab your popcorn). I don't in fact remember precisely that I got rid of almost all of them but that was my intent and it's what I see logged in as admin, too.

**Comment by luizaogs** [comment] 2022-06-30 16:35
Ha ok good. So I think this is fine?

**Comment by luizaogs** [comment] 2022-06-30 16:42
(Ok so I guessed that Omar's password was "food" before watching that tutorial. My three guesses were "meow," "food," and "poop", and I got it in 2!)

**Comment by urapadmin** [comment] 2022-06-30 16:50
I have deleted at least one, too. So one is correct, from my perspective.

**Comment by urapadmin** [comment] 2022-06-30 16:51
meow?

**Comment by urapadmin** [comment] 2022-06-30 16:51
That's not Omar :o) The other two definitely are.

**Comment by luizaogs** [comment] 2022-06-30 16:58
You’re right, the other guess should’ve been “lick” or “belly”

**Comment by urapadmin** [comment] 2022-06-30 16:59
or cute :o) Because she still kinda is. I'll close this (although that is a bit illegal for developers)

**Comment by urapadmin** [comment] 2022-06-30 16:59
we clicked at the same time :o)

**Closed** 2022-06-30 16:59 UTC
Labels: bug, kiosk

**Comment by lbestock** [comment] 2022-06-30 21:28
She is cute, even though hot lying on me on a warm day. And bald of belly. And apparently really happy currently. Also, if you caught the moment of panic in my eyes on camera that was when I almost said poop on video and did a quick change to my intended password. So, nice job :)

**Comment by luizaogs** [comment] 2022-07-01 02:05
I did catch it :) And thought it was really funny.
