### ISSUE TITLE
buap: switch from total free input to domain/serial free input

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#2956] opened 2024-11-02 22:02 UTC
To match what would be the identification method for loci if BUAP were actively digging, we would have to use temporary free input - but permanently as long as we input legacy data. 
That needs some more explaining to do.

Perhaps I should make a particular identification method that isn't temporary free input and separates unit/locus automatically for BUAP? 

- [x] what definitely must happen is converting all current inputs once to match the domain/serial number pattern.
- [x] I guess the most reasonable thing here would be an input that splits unit and locus. Unit can use the current unit as default

**Comment by urapadmin** [comment] 2024-11-04 01:07
I guess the most reasonable thing here would be an input that splits unit and locus. Unit can use the current unit as default.

**Comment by urapadmin** [comment] 2024-11-04 02:33
### recording app 16.4
- new identification method "idgen_input_domain_and_serial" asks for free input of both domain and serial id in separate fields
- when in temporary free input mode users are allowed to change the domain otherwise the domain has a default that cannot be changed.
- for BUAP we use it for unit (the domain) and locus# (the serial id)

**Comment by urapadmin** [comment] 2024-11-04 02:34
don't close this until all of the checkboxes in the header are done!

**Comment by urapadmin** [comment] 2024-11-04 02:50
documented here: https://wiki.arch-kiosk.brown.edu/urapdev/doku.php?id=manuals:developer_manual:common_identification_methods#buap_style_legacy_locus_creation
and here:
https://wiki.arch-kiosk.brown.edu/urapdev/doku.php?id=manuals:developer_manual:context_identification_-_generation_functions#idgen_input_domain_and_serial

**Comment by urapadmin** [comment] 2024-11-04 15:31
@arch-kiosk/test  I have added that identification method to PVD and created a unit BUAP that is using it

**Comment by luizaogs** [comment] 2024-11-04 16:43
The identification method is working as intended so I remove this from testing but do not close it because of the remaining checkbox.

**Comment by urapadmin** [comment] 2024-11-05 00:26
the first part brought up complications:
While it was no problem to split an identifier like "147-1" into the domain "147" and the serial number 1, I ran into loci like "147-1b" and the b kills it.

I have solved it now so that I turn the second part into whatever number I can make of it ignoring any non-number. So 147-1b leads to 1. So would 147-b1blah etc. 
The result, of course, is that we most likely have duplicate serial numbers in such cases. But that does not harm. They are used only to sort and to find the next number when using a sequential identification method.

But it leads to a new task: 
The identification method I invented above must accept 147-1b as well.
This is the plan:
- [x] Under normal circumstances it does not accept non-numbers in the second part of the identifier. You get an error in this case.
- [x] if temporary free input is on you'll get a warning but if you proceed the result will do exactly what I described above: any numerical part of the input will be mushed together and interpreted as the id. 14b leads to 14, likewise 1b4c. So our locus 147-1b will get the serial number 1.

**Comment by urapadmin** [comment] 2024-11-05 00:28
### Kiosk 1.6.6.6 (yeah)
- [x] BUAP gets proper domain and serial number for all current identifiers

**Comment by urapadmin** [comment] 2024-11-05 04:09
### recording 16.4.4
- the idgen_input_domain_and_serial refuses non-numeric locus ids now
- if in temporary free input it accepts them eventually after a warning
- The result of a non-numeric serial id is the integer that you get when ignoring the non-numeric digits. So x12c would lead to 12.
- if the result is correct can be checked easily by switching test mode on. The header of the locus layout reveals the domain and the id: 
![image](https://github.com/user-attachments/assets/315ddb82-5d91-485b-844b-87e926385d2d)
- unfortunately this has implications way beyond creating loci in buap. It is a major change to the whole system that creates identifiers and can potentially make it impossible to create a new identifier. This is so hard to test that we need a new ticket for that alone: #2968

**Comment by urapadmin** [comment] 2024-11-05 04:56
- see also #2967

**Comment by urapadmin** [comment] 2024-11-05 05:38
@lbestock 
I have found locus 172-18 which has a 18a and a 18b. That would never trigger the anc import because there are no As or Bs. So if you ever want to import those collected materials at least one locus would have to be 172-18. I suggest that the policy is to name what looks like the major locus without a letter and then the other(s) with a letter,

There is also a 175-15b but no 15a or 15, I think (my list here is not perfect)
same with 172-40B. No 40 or 40A

But those are all loci with letters that I can see at all.

**Comment by lbestock** [comment] 2024-11-05 15:47
Unless one can figure out which ANC#s actually belong to which of the two, which might be possible from the notebooks. In that case the solution would be to amend the locus number in the ANC database itself, and then it would slurp it right up.

**Comment by lbestock** [comment] 2024-11-05 15:50
There are 175-15 and 172-40. Which is what I would expect - an "A" means someone went back in and renamed the first of the double. On entry it wouldn't have been known there was a second.

**Comment by lbestock** [comment] 2024-11-05 16:15
What would happen if I made a change in the ANC database to a record that was already imported? As in, if something was already brought in as 175-15, and then I decided I could tell that it was 175-15B and changed that in the ANC database? Would it import it properly into 15B, and would it remove it from 15? Or should I, once I realize this, delete it from 15, change it in the ANC database, and let it be imported anew and properly?

**Comment by lbestock** [comment] 2024-11-05 16:45
In testing #2968 I have tried to change the domain for an ANC number that was originally brought in to 175-15. I changed it to 175-15b. That works in the temporary free input but we need to specify that this is NOT the way to do it. That CM stays in 175-15, and nothing in the record makes it look to the user like 15b.

We have discussed this a lot in recent days and I'm still somewhat confused about what the domain does there when the CM ID number does not include the locus. I can change it to something bonkers and it has no apparent affect on my CM list in the BUAP configuration.

**Comment by urapadmin** [comment] 2024-11-06 00:23
> In testing #2968 I have tried to change the domain for an ANC number that was originally brought in to 175-15. I changed it to 175-15b. That works in the temporary free input but we need to specify that this is NOT the way to do it. That CM stays in 175-15, and nothing in the record makes it look to the user like 15b.
> 
> We have discussed this a lot in recent days and I'm still somewhat confused about what the domain does there when the CM ID number does not include the locus. I can change it to something bonkers and it has no apparent affect on my CM list in the BUAP configuration.

Because BUAP has the wrong identification method applied in collected material. Apparently it is locus-serial number and that, correctly, asks for domain / serial number in temporary free input. We need to switch BUAP to plain free input (and no domain).
As that is configuration only, I'll leave it to you.

**Comment by urapadmin** [comment] 2024-11-06 00:34
> What would happen if I made a change in the ANC database to a record that was already imported? As in, if something was already brought in as 175-15, and then I decided I could tell that it was 175-15B and changed that in the ANC database? Would it import it properly into 15B, and would it remove it from 15? Or should I, once I realize this, delete it from 15, change it in the ANC database, and let it be imported anew and properly?

First of all we would have to find out where the latest ANC DB is. I guess I would be able to find that.
Then you would have to make the changes there.
Then I would have to import that into the ANC copy in Buap (lives in the background).

Let's say collected material 512 has locus 175-15b and lot 1 in the anc db. If there is a locus 175-15b and a lot 1 in BUAP, that would pull the collected material 512 in. BUT. it would NOT delete the same one that already got pulled in to 175-15 back in the days. So you would have to delete that first.

- Not a good way of dealing with this problem. We better add a feature that allows us to move a collected material over to a different locus: #2976

**Comment by urapadmin** [comment] 2024-11-06 00:48
can we close this otherwise? Please close tickets. I am drowning.

**Closed as completed** 2024-11-06 02:13 UTC
Labels: filemaker recording, BUAP
