### ISSUE TITLE
configuration search failed to return expected results

### ISSUE THREAD

**Issue by lbestock** [arch-kiosk/arch-kiosk-office#2058] opened 2023-04-21 14:01 UTC
I am testing and was looking for test mode and thought I could find the configuration key quickly by searching for test. But this didn't work. Is this because I am misusing configuration search or is something up?
![image](https://user-images.githubusercontent.com/49291909/233655784-dd035cb6-f9f5-493f-a7c4-1615f33ba68d.png)

**Comment by urapadmin** [comment] 2023-04-21 14:17
ja, I went a bit overboard here with the filtering. It keeps you from finding anything in "admin", "system" and "html" and it suppresses everything obsolete. Unless you are in development mode, which is just me, So you cannot find things in places where normal admins mustn't go.

**Comment by urapadmin** [comment] 2023-04-21 14:27
in other words: That is intended behaviour and I close this.

**Closed by urapadmin** 2023-04-21 14:27 UTC
Labels: filemaker recording, user manual
