### ISSUE TITLE
fields will not allow input for locus type: grave with additional fields burial

### ISSUE THREAD

**Issue by lbestock** [arch-kiosk/arch-kiosk-office#552] opened 2020-04-22 15:33 UTC
v. 8.9.15 newly wiped USTP on Alice.
I created a locus of type grave. In fact I made a mistake - it should have been burial. I was perplexed to see no MNI and burial type, so I went to admin: locus types, and turned on the bu additional fields that are there for locus type: burial. I returned to my locus and the fields were now there, but I am unable to put anything in them - I can't click on them. Neither the free input minimum number of individuals, nor the burial type drop-down menu, works. This is NOT broken when I create a new locus of locus type: burial - there I can put information in the same fields with no problem.
Here's where I am - it doesn't look like anything because I can't click in these boxes to call up my keyboard:
![image](https://user-images.githubusercontent.com/49291909/80001944-fc376c80-848c-11ea-9ac4-eb08f4c021fd.png)

**Comment by urapadmin** [comment] 2020-04-22 17:02
that is a bit of a test problem. I would rather not stretch myself to catch that somewhat rare case. The issue is: When you selected grave it had no field set. You went to config and gave it one and then back to the locus. The layout for the field set is there but no record for it. That record is created when selecting the locus type. So just select the context type again (by changing it to something else and then back) and there you are.

**Comment by urapadmin** [comment] 2020-04-22 17:03
but leave it open, perhaps an elegant, non intrusive way to deal with the rare case comes up.

**Comment by urapadmin** [comment] 2022-06-17 18:42
no, I close this because it really is just a test issue

**Closed by urapadmin** 2022-06-17 18:42 UTC
Labels: enhancement / extension, filemaker, minor/low priority
