### ISSUE TITLE
a user's computer is crashing with creation of loci

### ISSUE THREAD

**Issue by lbestock** [arch-kiosk/arch-kiosk-office#2954] opened 2024-11-01 19:54 UTC
New BUAP user working on a Mac laptop (we'll get him signed up to GitHub momentarily). Every time he makes a new locus number, FM crashes. The locus is there when he logs back in, but that's weird.

FM version: recently downloaded 2021 
MacBook pro 2020 (definitely pre M1 at least)

**Comment by lbestock** [comment] 2024-11-01 20:58
Interesting problems noted at import and synchronization with the same user.
@ThomasHaunstetter

**Comment by lbestock** [comment] 2024-11-01 21:06
Tom has emailed me the photos so we can look at them at least this weekend, but they are just HEICs so this really should have worked.

**Comment by urapadmin** [comment] 2024-11-01 23:45
This has nothing to do with the photos. That's #2955 

As for the crashing loci, which we really have never seen anywhere, I am at a loss. Needless to say that I can't reproduce that here, either.

Let's see if it simply vanishes when he switches to FM20, which is necessary because FM21 has trouble again with HEICS.

**Comment by urapadmin** [comment] 2024-11-04 15:25
@ThomasHaunstetter I am hoping that the crashes when adding a locus will be solved by switching to FM 20. Otherwise I am really at a loss right now as to what might be causing this. Can you please tell me your MacOS version?

- See #2959

**Comment by urapadmin** [comment] 2024-11-16 00:57
I close this until it reappears.

**Closed as completed by urapadmin** 2024-11-16 00:57 UTC
Labels: 🐞 bug, filemaker recording, 📞 support-ticket
