### ISSUE TITLE
bridge: file upload errors

### ISSUE THREAD

**Issue by lbestock** [arch-kiosk/arch-kiosk-office#1918] opened 2022-11-07 12:41 UTC
I have been trying to upload a file to urap-test via bridge. I have not made any new data in there, but it was patched and wanted an upload and syncrhonization.

The first time it failed, I received this error:
![DB3483A1-BBEE-4BC8-9C54-7C6FD0A8674E](https://user-images.githubusercontent.com/49291909/200312127-388865f7-bd82-4cbb-a0c8-c43b91c2cfff.png)

As the iPad had gone to sleep I thought that was likely a problem and I reset the sleep settings so it would stay on. I tried again, and I got that error again, but thought since I had been in another app perhaps that was messing things up.

But I went and stayed in bridge for the next upload and then it was weird. First, shortly after starting, there was a network error and bridge said it had no connection. I refreshed it and it connected again and went on with the upload, with the status bar moving. But a couple of minutes later I got this:
![67FA04A7-8E94-4F18-8C53-D0DB412F03F1](https://user-images.githubusercontent.com/49291909/200313098-cd4d4774-0d4c-4e1b-8ce5-c932734eab1a.png)

A final time there were no hiccups in the process, but I got the same 400 error in the end.

**Comment by urapadmin** [comment] 2022-11-07 14:47
On Beset you have to go through the Browser for the time being (at least for the upload).

**Comment by urapadmin** [comment] 2022-11-07 16:53
so did I. And although I know what is wrong and where, I don't have the capacity to do anything about it without running into danger of messing up core functionality. The Covid 🧠 is pretty limited.

**Comment by urapadmin** [comment] 2022-11-08 23:27
### kiosk 1.2.9
the provisional solution is active on urap-test and should allow you to use KioskBridge for uploads, too.

**Comment by urapadmin** [comment] 2022-11-10 19:57
this is a duplicate of #1888 So I close this here.

**Closed by urapadmin** 2022-11-10 19:57 UTC
Labels: bug, kiosk, KioskBridge
