### ISSUE TITLE
Bridge: failure at upload

### ISSUE THREAD

**Issue by lbestock** [arch-kiosk/arch-kiosk-office#2189] opened 2023-06-07 14:52 UTC
We have been able to replicate a Bridge problem Leslie was having in the field so now Lutz can study it. Testing with USTP, which is a pretty big (c. 350MB) file. Black iPad. Sending to Kiosk was fine, but the instant I hit upload it crashed. Lutz sent it again, and then uploaded successfully. There are two logs. One is basically blank, like Leslie's. The second one I attach here.
[kioskbridgelog2.txt](https://github.com/arch-kiosk/arch-kiosk-office/files/11678865/kioskbridgelog2.txt)

**Comment by urapadmin** [comment] 2023-06-08 02:57
Do you add a few lines about the issue and what appears to be a remedy (re-transmitting the filemaker file) at least at times to the Q&A?

**Comment by urapadmin** [comment] 2023-06-08 13:42
no, this is definitely an issue I'll have to tackle.

**Comment by urapadmin** [comment] 2024-05-24 04:06
I did address this back then and added a few lines to the Bridge project.
I am not sure it helped, so some testing is necessary here,

**Comment by urapadmin** [comment] 2024-05-24 04:08
it needs a slower (older) iPad and a bigger database (khpp or PACHA or something like that) so that the transfer from FileMaker Go to Bridge takes a bit and makes users impatient. They then will click again in FM GO, thinking nothing happened on their first click and that will send the file again to FM Go. And that is somehow how the issue was triggered in my theory.

**Comment by luizaogs** [comment] 2024-05-24 04:23
You wanted me to use my iPad for this? Not sure it qualifies as "older".

**Comment by urapadmin** [comment] 2024-05-24 04:27
it does!

**Comment by urapadmin** [comment] 2024-05-24 04:28
but @lbestock needs to attack that, too. It was hard to reproduce (although Leslie claimed it happened all the time to her)

**Comment by luizaogs** [comment] 2024-05-24 04:28
Ok. Another Saturday project for me.

**Comment by luizaogs** [comment] 2024-05-25 16:06
> it needs a slower (older) iPad and a bigger database (khpp or PACHA or something like that) so that the transfer from FileMaker Go to Bridge takes a bit and makes users impatient. They then will click again in FM GO, thinking nothing happened on their first click and that will send the file again to FM Go. And that is somehow how the issue was triggered in my theory.

Wait I'm a bit confused with this description. I am testing if there are issues sending the database to FM, or sending it back? Or both?

**Comment by urapadmin** [comment] 2024-05-25 16:20
The issue that Leslie had and that we were able to reproduce finally happened when uploading the database to Kiosk - Bridge would simply "crash" - I suppose it just closed without a message, can't remember. BUT I think that was only an effect of what actually happened earlier when transferring from FileMaker Go TO Bridge. With bigger databases that can take a while but nothing seems to happen for the user. So user gets impatient an while one transfer is still happening they click again in FileMaker. And that didn't always go well on the Bridge side. But that there was a problem would only show when uploading to Kiosk -> crash.

That is how I remember it.

**Comment by luizaogs** [comment] 2024-05-25 16:47
Ok yeah. I just got a crash using PACHA. 

I clicked on upload in Bridge, nothing seemed to happen (there was no uploading .... message) so I clicked again. Crash.

**Comment by luizaogs** [comment] 2024-05-25 16:48
PACHA crashed again, and this time I only clicked once. The "upload to Kiosk" button faded and then it crashed.

**Comment by urapadmin** [comment] 2024-05-25 16:52
okay. That proves the issue is not solved. Now if you apply what the Q&A suggests in this case, can you make it work next time?

**Comment by luizaogs** [comment] 2024-05-25 16:56
This? 

"If Bridge quits on you immediately after you hit “upload to Kiosk” then you may need to resend the Filemaker file to Kiosk. Just go back to Filemaker, select your file, and send it again. In tests we have most often had this problem when we are clicking at lightspeed, and so waiting patiently and making sure not to double-click may also help."

No. Resent the file, didn't double click, Bridge crashed after I clicked on upload.

**Comment by urapadmin** [comment] 2024-05-25 17:09
great. Okay, so that doesn't help. Can you please go to the Bridge settings. There is an option to get a log. Please send the one you get after you transferred to Bridge. aand then whatever you get after you restart Bridge after the crash. to me. I gave little hopes, though. The logs were usually strangely empty.

**Comment by luizaogs** [comment] 2024-05-25 18:05
Here is the log after transferring to Bridge: 
[kioskbridgelog.txt](https://github.com/arch-kiosk/arch-kiosk-office/files/15444488/kioskbridgelog.txt)

**Comment by luizaogs** [comment] 2024-05-25 18:06
Well godddammit, now it says the upload was successful of course.

**Comment by luizaogs** [comment] 2024-05-25 18:06
After successful upload: 
[kioskbridgelog 2.txt](https://github.com/arch-kiosk/arch-kiosk-office/files/15444493/kioskbridgelog.2.txt)

**Comment by luizaogs** [comment] 2024-05-25 18:07
I'm going to try and get a crash again ...
The only thing I notice I did differently is that, when going to transfer it to Bridge this time, I accidentally clicked on the file in FM and saw the login screen.

**Comment by luizaogs** [comment] 2024-05-25 18:26
After sending to Bridge: 
[kioskbridgelog.txt](https://github.com/arch-kiosk/arch-kiosk-office/files/15444566/kioskbridgelog.txt)

Goddammit! It uploaded again.

**Comment by luizaogs** [comment] 2024-05-25 18:26
Lutz. Help.

**Comment by luizaogs** [comment] 2024-05-25 18:27
> could you tell me your iOS version and iPad model?

iOS 17.1.1, iPad 9th generation

**Comment by urapadmin** [comment] 2024-05-25 19:47
ja, that's the goddamn problem with this goddamn error. It is like quantum mechanics. I never can actually look at it or log it or anything. That makes it smell totally like a timing issue somewhere. The goddamn thing.

**Comment by luizaogs** [comment] 2024-05-25 20:09
Blah should I just try it again?

**Comment by urapadmin** [comment] 2024-05-25 21:45
no, you would just ruin your day. I have an old iPad mini here that shows the same and makes a mess with PACHA. The transfer from FileMaker to Bridge was way too fast for more than 600MB of database. and so I still think the issue lies around there. But I can't nail it down because the logs are always gone after the crash.

I take it from here

**Comment by urapadmin** [comment] 2024-05-25 21:49
and then when it started the upload it clearly didn't really upload anything coherent (again way too fast) and the result was that on the server side:
![image](https://github.com/arch-kiosk/arch-kiosk-office/assets/38838314/ca0b1ab3-acee-4f6c-a366-92428a3cc40b)

**Comment by urapadmin** [comment] 2024-05-25 22:00
nothing really works with that gd iOS apo. I deleted and re-installed it, hoping that the "unsafe mode" would allow me to send the file to Bridge even though it is not in the proper state. Does not work. Arg.

**Comment by urapadmin** [comment] 2024-05-25 22:01
I will postpone that in favour of the likewise puzzling #2644. When the local server is ready and Kiosk 1.6 rolled out, I'll come back to it.

**Comment by lbestock** [comment] 2024-05-28 16:36
You intend to do this today, though? I just saw in the Q&A that we mentioned it would be solved before 2024. Needs an update either way.

**Comment by lbestock** [comment] 2024-05-28 17:00
I have forced an error that @urapadmin says may be somewhat different but as it culminates in the same point, wants added here. I sent my FM file to Bridge. I hit upload in Bridge. I immediately hit it again, and this made Bridge crash. But the file itself was fine - I reopened Bridge, uploaded less impatiently, and Kiosk imported the file with nary a complaint.

**Comment by urapadmin** [comment] 2024-06-02 23:19
### Bridge 0.2.4 (8)
KioskBridge is a Horror Movie in which I am the butcherer and the victim all in one. That code is so embarrassing. 
But I have changed the upload and other things so substantially that this needs a complete test:

- when hitting the 24 log button in settings it should immediately show a progress indicator that runs while the logs are prepared (who knows why compiling a few lines of logs takes soooo long). It should not be possible to hit that button twice.

- when hitting any button like download, upload, send to FileMaker or whatnot, the button must turn to a disabled state while the process is ongoing. It should not be possible to hit that button twice (we had that particularly with the upload button, that's the error @lbestock ran into)

- The real issue is the size of the File that comes from FileMaker. With PACHA (>600MB database) I was able to reproduce the crash reliably on an older iPad. Even newer iPads might run into a limit. The issue is that KioskBridge was requested more Memory than necessary during upload and it was doing that synchronously, blocking the UI of the app. Now it is not blocking the App anymore and I have done several, horrible things to reduce the amount of memory that is required during the process.

- So now even PACHA should work on an older iPad or an iPad that is already under Memory strain.

**Comment by urapadmin** [comment] 2024-06-02 23:21
This is all so particularly bad because Apple's iOS does not support the most common file upload protocol used on the internet. And that's the one that Kiosk is supporting, currently. To stabilize this finally and make it consume even less memory than right now Kiosk would have to support the file transfer protocol that iOS is supporting. That is for another ticket:

**Comment by urapadmin** [comment] 2024-06-03 15:54
it might make sense to monitor the memory consumption of Bridge: https://stackoverflow.com/questions/40991912/how-to-get-memory-usage-of-my-application-and-system-in-swift-by-programatically

**Comment by urapadmin** [comment] 2024-06-03 16:07
@luizaogs I have the feeling we were testing with the same dock Pachapad01 at the same time and interfered with one another.

**Comment by urapadmin** [comment] 2024-06-03 16:09
at least all of a sudden Bridge told me after a long upload that Kiosk refused to accept the upload and when I looked the dock was back to ready for download. So I think I'd better not take that seriously.

**Comment by luizaogs** [comment] 2024-06-03 16:09
> at least all of a sudden Bridge told me after a long upload that Kiosk refused to accept the upload and when I looked the dock was back to ready for download. So I think I'd better not take that seriously.

No, don't. That was me.

**Comment by urapadmin** [comment] 2024-06-03 16:11
I'll try with my own dock. Could you also please try a different project, like USTP?

**Comment by luizaogs** [comment] 2024-06-03 16:12
Ok.

**Comment by luizaogs** [comment] 2024-06-03 16:15
I'll do URAP.

**Comment by urapadmin** [comment] 2024-06-03 16:23
just had a crash with PACHA on upload. So this is not entirely over. But I was able to restart Bridge and when hitting upload again it started and is over the critical part now. Not perfect but improved, it seems.

**Comment by urapadmin** [comment] 2024-06-03 16:23
I'll do USTP.

**Comment by luizaogs** [comment] 2024-06-03 16:27
Hm. Crash with URAP on upload, too.

**Comment by luizaogs** [comment] 2024-06-03 16:28
But yeah, after I entered Bridge again I was able to click on upload and it seems like that is working.

**Comment by luizaogs** [comment] 2024-06-03 16:30
Weird. Bridge quit, seemingly during the upload, but when I go back in it says "upload again" and Kiosk says it has been uploaded and tells me to import.

**Comment by urapadmin** [comment] 2024-06-03 16:35
hmpf. That is still not very satisfying.

**Comment by urapadmin** [comment] 2024-06-03 16:36
my pacha upload worked fine and Bridge did not crash again.

**Comment by urapadmin** [comment] 2024-06-04 03:35
### Kiosk Bridge 0.2.5

> it might make sense to monitor the memory consumption of Bridge: https://stackoverflow.com/questions/40991912/how-to-get-memory-usage-of-my-application-and-system-in-swift-by-programatically

- It is showing its own memory usage in the upper right corner now. Updated every 10 seconds or earlier. 
- Apart from that I have not been able to do anything further to make it more reliable. Currently it seems that in terms of a crash a restart sets the app back to lowest memory consumption and that is enough to restart the upload. Until #2755 this seems to be the best I can come up with,

**Comment by luizaogs** [comment] 2024-06-04 19:28
I see the memory usage now, so I guess I'll close this in favor of #2755

**Closed by luizaogs** 2024-06-04 19:28 UTC
Labels: 🐞 bug, A: next!, KioskBridge
