### ISSUE TITLE
Kiosk: Dates keep reversing to 1/1/0001

### ISSUE THREAD

**Issue by maychu16** [arch-kiosk/arch-kiosk-office#2430] opened 2023-12-21 21:32 UTC
I am trying to put the date in images/unit narrative. Everytime I type in the date and click on another field to keep working, the date field keeps reversing back to 1/1/0001 12:00 AM. I am on macos 13.5.2, and FileMaker Pro 19.6.3.302. 

<img width="1026" alt="Screenshot 2023-12-21 at 4 29 29 PM" src="https://github.com/arch-kiosk/arch-kiosk-office/assets/153842762/dbcf1a6d-1e17-425f-817d-f92556948e46">

**Comment by urapadmin** [comment] 2023-12-21 21:35
that is not supposed to happen. What exactly did you type in and how do you leave the field (mouse, keyboard?).

**Comment by maychu16** [comment] 2023-12-21 21:36
I typed in 12/29/2010. Then I used my mouse to click on the field beneath to start typing the narrative.

**Comment by maychu16** [comment] 2023-12-21 21:39
I somehow found a workaround for the bug. If I clicked that orange icon that looks like a name tag, the screen changed and I can type in the correct date and it doesn't change back to 1/1/0001 12:00 AM. 
<img width="1512" alt="Screenshot 2023-12-21 at 4 39 03 PM" src="https://github.com/arch-kiosk/arch-kiosk-office/assets/153842762/1c17353a-241d-4c07-848d-398272adb882">

**Comment by maychu16** [comment] 2023-12-21 21:44
Never mind, the workaround stopped working for my second narrative box. It is now back to reversing to 1/1/0001 12:00 AM

**Comment by urapadmin** [comment] 2023-12-21 21:58
could you please try the latin way: 29.xii.2010?

**Comment by maychu16** [comment] 2023-12-21 22:05
That worked! Thank you.

**Comment by urapadmin** [comment] 2023-12-21 22:07
that is just a workaround, though. I can reproduce the bug and will fix it for the next version. I just wanted you to have a way to move on without an update.

**Comment by maychu16** [comment] 2023-12-21 22:07
This is just a minor problem but when I tried to change the time, it still reverses back to 1/1/0001 12:00 AM. I was typing in 12/xii/2010 08:40 AM. 
<img width="1512" alt="Screenshot 2023-12-21 at 5 06 47 PM" src="https://github.com/arch-kiosk/arch-kiosk-office/assets/153842762/d60319ad-e5e7-430b-8c4f-a98c379caa39">

**Comment by urapadmin** [comment] 2023-12-21 22:08
good to know. That might help me wrap my head around what's going on.

**Comment by urapadmin** [comment] 2023-12-21 22:10
you can also use a European date: for now 10.12.2010 works as well.

**Comment by maychu16** [comment] 2023-12-21 22:14
that format did not work for me.

**Comment by urapadmin** [comment] 2023-12-21 22:16
sorry, Your example was 29.12.2010. But it is possible that it only works because I am on a EU setting. In fact some US dates work, or rather SEEM to work: 10/12/2010 is accepted at least on my machine BUT turns out as 10.XII.2010. So this is really not getting a US date properly. That's dangerous. So I copy @lbestock and @hschaef1 here to warn them. 

I am on it.

**Comment by urapadmin** [comment] 2023-12-21 23:04
wow. FileMaker is not dealing with US dates correctly if the FileMaker database was created in a different country. One of those numerous bugs that are known since version 6 and will not be fixed in my lifetime. 

### recording 15.7.3
I am trying to work around that bug now. But it is, erm, a somewhat wonky solution. Please test! 
- The date fields should allow for proper dates in the format of the current machine's operating system settings (so in you guys' case US) or with the latin date that we invented. That one is always day.latin-month.year (the separator can vary or even be left out when using the latin format)
- Make sure that US dates turn out correctly in the latin format that is shown below the input field. It is easy to overlook that month and day are switched. And that is exactly what happened because of the FileMaker bug: It would interpret the date as a German date but accept a US separator (the / ).

**Closed** 2023-12-23 18:53 UTC
Labels: 🐞 bug, filemaker recording
