### ISSUE TITLE
synchronization: identification method not synchronized

### ISSUE THREAD

**Issue by lbestock** [arch-kiosk/arch-kiosk-office#1744] opened 2022-07-09 19:39 UTC
I need to run through this again to make sure because it seems unlikely?

But I am testing recording 13.3 and as one change was to make more room for insane locus numbers, I switched the ID method for loci to be insane. I did it the super fast way first, by making the prefix absurd. On synchronizing and downloading again and going back to ID methods to make the method actually conform to what PACHA is using, I was surprised to find that the prefix is set back to what it had been before my insanity.

**Comment by lbestock** [comment] 2022-07-09 19:41
(It IS set to the same way PACHA does it - PACHA numbers are long because their unit names are so long, and those are free input.)

**Comment by lbestock** [comment] 2022-07-09 19:55
Indeed, this does not survive synchronization and is definitely one for the developer. 
What I have done most recently to check it:
In pacha-test I downloaded. I am running 13.3 on iOS 15.5, FM Go 19.5.1.31, and kiosk is at 0.25.6
I went in to admin, ID methods. In loci I added a prefix to the existing -. This time, since you are walking on the Rhein (I almost said Nile - archaeology brain) I made the prefix "nutria". As you can see in the developer's log for today, I made two new loci that correctly applied this prefix.
Logged out, uploaded, imported, synchronized, checked that developer's log.
Prepared and downloaded. The loci are there as they should be. But in going back to ID methods, the "nutria" is now absent and of course is not applied if I make a new locus. Why didn't the ID method syncrhonize?

**Comment by urapadmin** [comment] 2022-07-09 20:25
I don't know. Particularly because I just did almost the same thing: I added the partitions to the identification methods that same way and apparently that synchronized just fine.

**Comment by urapadmin** [comment] 2022-07-09 21:34
the synchronization log thinks the change got applied, if that is your change (does the timestamp suggest that?)
`5352/8488 7/9/2022 15:48:16 identification_methods: 1 changes applied to field formatting_parameters`

**Comment by lbestock** [comment] 2022-07-09 21:50
Yes that seems likely. But I really did check.

**Comment by lbestock** [comment] 2022-07-09 22:01
And it is still happening with the restored pacha-test.

**Comment by urapadmin** [comment] 2022-07-09 22:44
hm. I suppose it is a simple time zone issue. I am 6 hours ahead of you.

**Comment by lbestock** [comment] 2022-07-10 00:43
But how does that happen with the changes I myself made? On an iPad that's the same time zone as the server and all.

**Comment by urapadmin** [comment] 2022-07-10 11:10
I am interpreting my own system here rather than looking into it because I can't see this happening. I am am myself a bit in doubt about my theory because I saw a log of a change in identification methods in synchronization. 
But, the idea is this: I changed the SAME record 6 hours ahead. So you download my record and when you change it again, the new timestamp of that record is in fact set back 6 hours. Now in synchronization this timestamp is compared with the timestamp in the master db and you are back in time. So the record is not synchronized into the master db. And on next preparation you are back to where you were. And so is the timestamp. It is still 6 hours ahead because it is mine. So you can even repeat that over and over until the 6 hours have passed on your side of the ocean, too. 

And that's why here is the simple test:
Do it again now that more than 6 hours have passed.

If the issue is gone. I am right. (I just have to wrap my head around the synchronization log, but that's less critical).

**Comment by urapadmin** [comment] 2022-07-10 12:05
what does not add up here is that I have not changed the identification method for loci, at least not that I remember. I changed the identification methods for samples and special finds.

**Comment by lbestock** [comment] 2022-07-10 12:19
I have done a trial run here this morning and yet I still do not understand and you are having a hunch.

What I have done:
Prepared and downloaded pacha-test.
Changed the locus ID method to include a prefix (garden, this time).
Made a new locus, which was properly identified.
Uploaded and synchronized and all and checked the director's view to make sure my locus was in there properly. It was. To this point everything is just the same as yesterday.
Prepared and downloaded.
Made a new locus even before checking the ID methods and lo and behold, it was prefixed with garden.

So it would seem that this time the same type of change did properly synchronize and so your prediction was correct, but I still want to understand how that could be. You hadn't messed with the locus ID method yesterday so in terms of you applying a change that would overwrite my own I can't see how? And if it were a matter of everything being new from your end, then why did it accept other changes that I made, like the addition of myself as a FM user, and the loci themselves?

**Comment by lbestock** [comment] 2022-07-10 12:20
Also worth remembering in here is that I got this twice before I catastrophically wiped out all the data with the last vestige of the one-click nuclear bomb, and once after.

**Comment by urapadmin** [comment] 2022-07-11 18:34
I studied the logs. My hunch is again not supported by the logs. And also not by what we had actually been doing. You changed the formatting_parameters of the identification_method for loci and I changed the generation_parameters for samples and small finds. Different records. 
That's me:
```
Syncing "identification_methods".""id"
>[8516/6288: synchronization.DEBUG at 2022-07-09 14:48:39,166]: Syncing "identification_methods".""display_name"
>[8516/6288: synchronization.DEBUG at 2022-07-09 14:48:39,166]: Syncing "identification_methods".""description"
>[8516/6288: synchronization.DEBUG at 2022-07-09 14:48:39,166]: Syncing "identification_methods".""restricted_to_project_ids"
>[8516/6288: synchronization.DEBUG at 2022-07-09 14:48:39,166]: Syncing "identification_methods".""generation_function"
>[8516/6288: synchronization.DEBUG at 2022-07-09 14:48:39,166]: Syncing "identification_methods".""generation_parameters"
>[8516/6288: synchronization.INFO at 2022-07-09 14:48:39,166]: identification_methods: 2 changes applied to field generation_parameters
>[8516/6288: synchronization.DEBUG at 2022-07-09 14:48:39,166]: Syncing "identification_methods".""formatting_function"
>[8516/6288: synchronization.DEBUG at 2022-07-09 14:48:39,166]: Syncing "identification_methods".""formatting_parameters"
>[8516/6288: synchronization.DEBUG at 2022-07-09 14:48:39,166]: Syncing "identification_methods".""validation_function"
>[8516/6288: synchronization.DEBUG at 2022-07-09 14:48:39,182]: Syncing "identification_methods".""validation_parameters"
>[8516/6288: synchronization.INFO at 2022-07-09 14:48:39,182]: Synchronization._sync_modified_records: Table identification_methods: 2 records got new modification-dates.
```
And the logs show quite clearly that your one change was synchronized and transferred into the master database:
Syncing "identification_methods".""id"
```
>[5352/8488: synchronization.DEBUG at 2022-07-09 15:48:16,785]: Syncing "identification_methods".""display_name"
>[5352/8488: synchronization.DEBUG at 2022-07-09 15:48:16,797]: Syncing "identification_methods".""description"
>[5352/8488: synchronization.DEBUG at 2022-07-09 15:48:16,797]: Syncing "identification_methods".""restricted_to_project_ids"
>[5352/8488: synchronization.DEBUG at 2022-07-09 15:48:16,797]: Syncing "identification_methods".""generation_function"
>[5352/8488: synchronization.DEBUG at 2022-07-09 15:48:16,797]: Syncing "identification_methods".""generation_parameters"
>[5352/8488: synchronization.DEBUG at 2022-07-09 15:48:16,797]: Syncing "identification_methods".""formatting_function"
>[5352/8488: synchronization.DEBUG at 2022-07-09 15:48:16,797]: Syncing "identification_methods".""formatting_parameters"
>[5352/8488: synchronization.INFO at 2022-07-09 15:48:16,797]: identification_methods: 1 changes applied to field formatting_parameters
>[5352/8488: synchronization.DEBUG at 2022-07-09 15:48:16,813]: Syncing "identification_methods".""validation_function"
>[5352/8488: synchronization.DEBUG at 2022-07-09 15:48:16,813]: Syncing "identification_methods".""validation_parameters"
>[5352/8488: synchronization.INFO at 2022-07-09 15:48:16,813]: Synchronization._sync_modified_records: Table identification_methods: 1 records got new modification-dates.
```
So something got changed. I don't see how that could have been anything but your original change.

**Comment by urapadmin** [comment] 2022-07-11 21:17
It is a time zone issue. But, wow, not in synchronization. The change gets properly synchronized and even forked when the new workstation is prepared. It happens when exporting to filemaker. And this is why:
1. The number of records in the table identification_methods is still the same
2. The most recent change in the recording group's filemaker template is later than or equals the most recent change in the master db. BECAUSE: My last change in that table is 6 hours ahead of Laurel's due to the time zone.

And because of those 2 preconditions the export skips the whole table - simply because within the same time zone they indicate that the table is already up to date.

**Comment by urapadmin** [comment] 2022-07-11 21:21
good optimization, works.

Kiosk 1.2 is made for teams operation within the same time zone.

**Closed by urapadmin** 2022-07-11 21:21 UTC
Labels: kiosk, Beset, support-ticket
