### ISSUE TITLE
Kiosk: CMD+T must be prohibited

### ISSUE THREAD

**Issue by maychu16** [arch-kiosk/arch-kiosk-office#2431] opened 2023-12-21 23:38 UTC
I am on macos 13.5.2, and FileMaker Pro 19.6.3.302.

I don't know what exactly happened. I left my laptop for a bit to go have dinner. I did not log out of kiosk. When I came back about an hour later, it said "Attempt to save session excavating_session without access to that session table. This is an internal error. Please report it." and the whole recording system went blank. 
I logged out and logged back in again. The whole system is empty and I can't find any Op recordings. Not even the one that were already there when I first downloaded it. 
Please let me know how I should proceed. 

<img width="1512" alt="Screenshot 2023-12-21 at 6 33 01 PM" src="https://github.com/arch-kiosk/arch-kiosk-office/assets/153842762/92048235-56a7-4180-9b82-34a79b83dc20">
<img width="1512" alt="Screenshot 2023-12-21 at 6 33 46 PM" src="https://github.com/arch-kiosk/arch-kiosk-office/assets/153842762/72f40749-bf4b-434b-978d-16bcfea84e6f">

**Comment by urapadmin** [comment] 2023-12-22 00:57
I have a hunch. Please send me that file to the google drive: https://drive.google.com/open?id=13_O5Y-FJyenBSr_vG4ox-ucP1GrnAbe5&usp=drive_fs

I might be able to recover it

**Comment by urapadmin** [comment] 2023-12-22 01:09
before you do that: You have tried to select a site, right? If the site list box is empty, I need to look at that file. 

Otherwise I suspect once you have selected a site everything looks normal again. If that's the case I would suggest that you upload that file back to Kiosk asap so that we synchronize your latest changes. Just to be on the safe side.

**Comment by maychu16** [comment] 2023-12-22 01:21
I tried selecting a site but it is just empty and it shows an error message there too. I have uploaded the file to the drive link you sent.

**Comment by urapadmin** [comment] 2023-12-22 01:49
alright. My hunch was correct. I have never seen this before but I am not surprised that it happens now that we use FileMaker Pro for Mac. I cannot tell you how this happened, but a technical record got deleted. Perhaps by an unfortunate key combination or so? There I am tapping in the dark. If you have any hunch yourself on that front, I'd like to know your ideas.

However, the record was gone and after I recovered it everything was back to normal. 

I will add something to the start procedure for a future version that recovers this automatically on restart. For now I have updated your file in the google drive manually, please override your existing local file with this one.

**Comment by maychu16** [comment] 2023-12-22 02:06
Thank you. I can see the data now. Should I be logging out and closing kiosk every time I am gonna be away from my laptop in the future?

**Comment by urapadmin** [comment] 2023-12-22 02:21
I can't really see any connection between the issue and leaving FileMaker open. I would even be interested to hear that this happened again. Unless you have cats who hit keys in your absence I have no explanation.

**Comment by maychu16** [comment] 2023-12-27 03:00
I figured out what caused this by accident. It is Command + T on my mac.

**Comment by maychu16** [comment] 2023-12-27 03:07
It happened again and the program didn't recover my records after I restarted filemaker. So I restarted my laptop and opened filemaker again. It still did not recover my records.

**Comment by maychu16** [comment] 2023-12-27 03:18
I did not want to wait and I was playing around with filemaker to figure out how I can get my data back. After I chose file and then recover, filemaker created a new record file and that one has my records. So it is all good now.

**Comment by urapadmin** [comment] 2023-12-27 14:39
> It happened again and the program didn't recover my records after I restarted filemaker. So I restarted my laptop and opened filemaker again. It still did not recover my records. 
> 
> 
> 
> I uploaded my file in the drive you shared a few days ago. 

That was the right thing to do. I am not entirely certain but I think the recovery feature is not rolled out to BUAP, yet, as it had just been tested on our test system (we try to test things first on a test system before we hit production systems with bugs).

**Comment by urapadmin** [comment] 2023-12-27 14:47
> I did not want to wait and I was playing around with filemaker to figure out how I can get my data back. After I chose file and then recover, filemaker created a new record file and that one has my records. So it is all good now. 


Oh. Don't. The recovery tool does something entirely different and isn't without danger itself. That is true for all native FileMaker commands, so playing around with FM isn't a good idea (you were fine, you had a backup). The FM recovery tool also cannot possibly recover this situation even though it appears it has. Some coincidental side effect must have kicked in here. 
So, as annoying it admittedly is, patience was the right thing to apply here :)

Have you uploaded and synched this recovered version?

**Comment by maychu16** [comment] 2023-12-27 19:16
Ah sorry I did not know it could cause problems. I recovered the file, worked on it a bit and then synced it. I then downloaded a new file and synced that file too. So far I haven't ran into any problem. Should I be concerned?

**Comment by urapadmin** [comment] 2023-12-27 19:47
no, if the file got imported properly everything is fine. Afterwards it gets discarded, anyhow. Just for the future, don't try to help yourself with FileMaker tools - it is a dangerous path 😏

**Comment by urapadmin** [comment] 2023-12-27 19:56
@arch-kiosk/test, @arch-kiosk/buap 
I just looked up what CMD+T (CTRL+T on Windows) actually does. interesting. It is a filter command and omits the current record from the dataset. So it does not delete it but sets a filter. Ouch. That would not even be caught by #2432 because the record is actually there, just not shown. That also explains why the FM's recovery tool worked as it writes a new database and no filter settings survive that.    

So here is an immediate remedy: CMD+J (CTRL+J on Windows) removes that filter and all is good right away. I will also extend #2432 and try to find a way to suppress the whole filter option in the pertinent layouts.

**Comment by urapadmin** [comment] 2023-12-27 21:21
### recording app 15.9
- it should not be possible to use the CMD/CTRL+T on the Start page anymore (nor delete a record for that matter). I have reduced the FileMaker Menu for that layout.
- in all other layouts it should have never been possible as there was no layout. Please test this. You can always get your session record back with CMD/CTRL+J.

**Comment by lbestock** [comment] 2023-12-27 21:52
The issue is fixed for the start page in 15.9. But it IS possible in ALL other layouts that I have tried (trench, locus, CM) and it gets pretty baroque in CM:
![image](https://github.com/arch-kiosk/arch-kiosk-office/assets/49291909/9ee57eca-1546-4aa1-a919-2493d101a60d)

**Comment by lbestock** [comment] 2023-12-27 21:58
Wow it is possible to mess things up with CMD+T in:
inventory
ceramics
tag management (that one is scary - it doesn't look so abnormal, it just moves on to the next tag. And you can do it repeatedly and exclude a number of tags)
team members (ditto)
identifier lists
inventory

I could go on and test everywhere? But so far I have not discovered a layout where CMD+T is not causing this problem.

**Comment by lbestock** [comment] 2023-12-27 22:00
Ah, it does not seem to have an effect on tag analysis. A layout where one cannot put anything in.

**Comment by urapadmin** [comment] 2023-12-27 22:16
no, you don't need to go on. Apparently hiding the menu is not enough in the other layouts.

**Comment by urapadmin** [comment] 2023-12-27 22:18
### recording app 15.9.1
- please try again in loci and collected materal

**Comment by lbestock** [comment] 2023-12-27 22:26
At the locus list level it's now fine, but in loci themselves it is still causing havoc.
CM looks good.

**Comment by urapadmin** [comment] 2023-12-27 22:59
### recording app 15.9.2
- Loci should be fine now, too

**Comment by lbestock** [comment] 2023-12-27 23:15
It's good now in Loci. But not everywhere....inventory....

**Comment by maychu16** [comment] 2023-12-28 04:09
Did you also disable all shortcuts for filemaker? I cannot use CMD+C and CMD+V anymore. Not a problem but just wondering.

**Comment by urapadmin** [comment] 2023-12-28 04:18
- - yes, it is totally possible that that's a side effect. Now we have to figure out which short cuts we want ans which we don't. Cut, copy and paste we want ...

**Comment by maychu16** [comment] 2023-12-28 20:34
I think the side effect of this also makes me not able to import photos. I can't right click (I think it is right click or it could be left, not sure) on the image box anymore. It won't open up the insert photo/file tabs when I right click on it.

**Comment by urapadmin** [comment] 2023-12-28 21:19
oh. That is pretty severe. I was afraid we might have been battling the Teufel with the Beelzebub (German vor fighting the devil with something worse). I'll issue a new version tomorrow.

**Comment by urapadmin** [comment] 2023-12-29 14:56
### recording 15.9.3
- there is a configuration key "reduce_filemaker_menu" now. It is set to "yup" by default, which means CMD+T is prohibited (but also side effects might occur). If you encounter a side effect that keeps you from doing your work, you can go to the "admin" panel on the start page, go to "configuration" and then you find "reduce_filemaker_menu" under "visibility". Set this to "nope" and the side effect should be gone (but the CMD+T issue will be back, but you know how to remedy that). This configuration key does not sync, so it will be back to "yup" when you next download. 
- copy, cut, paste and necessary FileMaker abilities should be back now. But I cannot promise that I didn't miss something. Before you help yourself with the above config key, please report whenever you run into a missing feature like not being able to insert a file or so.

**Comment by urapadmin** [comment] 2023-12-29 15:19
### recording 15.10
- inventory should be protected against CTRL+T now, too

**Comment by luizaogs** [comment] 2023-12-30 06:45
The configuration key works as it should, and the commands we want (cut, paste, copy, insert images) are back. 

However, CMD+T is still problematic in: 
tag management
team members
identifier lists

^^ These are just the ones Laurel had already mentioned. Do you need someone to go through every single layout and check?

**Comment by urapadmin** [comment] 2023-12-30 17:21
> The configuration key works as it should, and the commands we want (cut, paste, copy, insert images) are back.
> 
> However, CMD+T is still problematic in: tag management team members identifier lists
> 
> ^^ These are just the ones Laurel had already mentioned. Do you need someone to go through every single layout and check?

First I want to let this loose on BUAP and see if there are other side effects that are not covered, yet.

**Comment by urapadmin** [comment] 2023-12-30 21:53
### recording 15.11.1
Tackled those:
- tag management
- team members
- identifier lists

**Comment by luizaogs** [comment] 2023-12-31 04:54
Those are good now. But I guess we keep this open then?

**Comment by urapadmin** [comment] 2023-12-31 15:51
I have so many open tickets. Let's close it and reopen it if needed :o)

**Closed by urapadmin** 2023-12-31 15:51 UTC
Labels: 🐞 bug, filemaker recording
