### ISSUE TITLE
coordinates not findable by identifier in FM search currently

### ISSUE THREAD

**Issue by luizaogs** [arch-kiosk/arch-kiosk-office#2009] opened 2023-03-24 14:11 UTC
Title is pretty self explanatory. From your testing instructions in #1986 it seemed like I should be able to search for the coordinate identifier in the FM search and that it would come up? It does not, currently.

(Unless you mean using the identifier to search elsewhere -- if that's the case, then nevermind.)

**Comment by urapadmin** [comment] 2023-03-26 18:57
no, I had not included it in the identifier search in FM. I am hesistating with that. In the end a point isn't an archaeological identifier in the sense of a collected material or so. Most users won't be concerned with points in their daily trench life. And I am a bit worried that a ton of points will clutter the search. I might make it optional (more config keys, yeahj).

**Comment by urapadmin** [comment] 2023-03-26 20:06
### kiosk 14.1.2
I did that. 
- the configuration key "search_coordinate_identifier" (in the config under "identification") is "yup" by default, so you can now search for coordinates in the identifier search.
- should a project not want that, we can switch it off with the config key
- the coordinates are only included if you have registrar status

**Comment by lbestock** [comment] 2023-03-27 01:04
I can search but for some reason it applies a filter. So I get my particular record in the search, and click on it and go to my record (Bob2 here). But then a filter for "backsites" is applied to the coordinates list.
![image](https://user-images.githubusercontent.com/49291909/227817222-2265ff77-566a-4a3e-9a2d-0dcc113414d3.png)
Particularly strange because then I'm in a record that is not in the list on the left, much as you just got rid of with #2008.

**Comment by lbestock** [comment] 2023-03-27 01:07
I am not quite sure what was intended with registrar status. If I sign in as someone without registrar status, I can still enter the coordinates area: coordinates and survey request are the only things available in the registration pane. I cannot search for coordinates by identifier at all, however. They don't show up as existing.

**Comment by lbestock** [comment] 2023-03-27 01:13
But I suspect that is the behavior you wanted in terms of registrar status. The configuration key works. If I set it to nope and then sign in as a registrar then my view of both search and coordinates in registration are the same as I just observed as a non-registrar. So I think this is good except for the application of the filter after searching.

OH WHOOPS.

I switched the configuration key back to "yup". And then logged out and logged back in as myself. And I cannot search for coordinate identifiers anymore. I logged out and in again as admin and the key is set properly back to yup...

**Comment by urapadmin** [comment] 2023-03-27 09:25
so here comes a "is the computer plugged in" question:
did you put ""yup"" in? Which means, did you input the inner double quotation marks? All configuration keys, of course, only want a "yup" (without the quotation marks).

I would not ask if I hadn't copy/pasted a ""nope"" recently. And I checked, it works fine for me.

**Comment by urapadmin** [comment] 2023-03-27 09:30
### recording 14.1.3
- you can't see the surveyor buttons anymore without registrar privilege
- I erase all filters when entering the coordinates. It is safer.

**Comment by urapadmin** [comment] 2023-03-27 16:38
> Testing in 14.1.3, and I still have the same problem with configuration - once I turn it to nope, then back to yup, I am still not able to search coordinates.
>
I downloaded your dock and tried it in your version and it works perfectly fine for me. I log on as admin (otherwise I could not change the config key), search for a point - find it. I go to config and change "search_coordinate_identifier" in "identification" to "nope", search again, can't find anything. I go back to config, change the same key to "yup", go back, search and there the coordinate is.
So you must do something else than I.
 
> As such, having done that first, I can't test the filter thing.
What has the one thing to do with the other (I mean, don't tell me closing your database and going back in still keeps you from searching for a coordinate)

**Comment by urapadmin** [comment] 2023-03-27 17:01
please upload that database as it is (don't import).

**Comment by lbestock** [comment] 2023-03-27 18:04
Uploaded, not imported.

**Comment by urapadmin** [comment] 2023-03-27 19:31
no, that wasn't "yup" in there. It was 
"yup
"
which means, there was a return behind the yup. That's not "yup" and not "yup" is "nope" in this case.

**Comment by urapadmin** [comment] 2023-03-27 19:31
I have changed it into "yup" and it works fine. So I close this.

**Closed by urapadmin** 2023-03-27 19:31 UTC
Labels: bug, filemaker recording

**Comment by urapadmin** [comment] 2023-03-27 20:28
it is a good example why quotation marks are even necessary: you would not know that the line break belongs to the value if it weren't within the quotes.
