### ISSUE TITLE
KHPP testing: creating a new lot created a new locus

### ISSUE THREAD

**Issue by lbestock** [arch-kiosk/arch-kiosk-office#2039] opened 2023-04-18 21:55 UTC
This is very weird because I cannot now replicate it, but I am sure it is what happened.

I had filled in basic information on a deposit locus I had recently created in KHPP.
I chose the lots tab.
I pressed the + button.
It gave me the usual "are you sure you want to create a new one" popup BUT it said "locus" instead of lot".
I thought huh, weird, that is labeled wrong.
I clicked it.
It did indeed create a new locus, not a lot. 
But now I've tried this again in a new locus and in the old locus and it is not repeated, so I am very confused. I really can't have gotten it all wrong - there is no dialog asking if you want to create a locus when you create a locus.

**Comment by urapadmin** [comment] 2023-04-19 00:54
hm. That might be indeed a late issue of the temporary free input changes from last year. I'll look into it.

**Comment by urapadmin** [comment] 2023-04-19 11:08
can't reproduce this. 
Please try to reproduce this yourself. Have you been somewhere else in between creating the locus and the lot creation that created a locus? Jumped back and forth or so? Temporary free input on? Where you admin or a normal user? All these things can potentially play into it.

**Comment by urapadmin** [comment] 2023-05-01 16:35
@luizaogs: You may have a stab at it and if you can't reproduce this, either, we close this.

**Comment by luizaogs** [comment] 2023-05-01 17:07
I cannot. So I close it.

**Closed by luizaogs** 2023-05-01 17:07 UTC
Labels: bug, filemaker recording, khpp
