### ISSUE TITLE
q&v: closing unit view leads opened locus or cm views with no data available

### ISSUE THREAD

**Issue by luizaogs** [arch-kiosk/arch-kiosk-office#2350] opened 2023-11-05 21:49 UTC
Uh will try to describe this in a way that makes sense. If I click on a context record from a unit record, then close the unit view and try to go back to the context record (which had remained open) I get a sad face that tells me there is no data available.

Steps: 
Run the what materials were found in unit x? query for LA.
Click on LA.
Click on context LA-022. Works.
Now close the window for LA with the x.
Click again on the LA-022 window (which you had left open) and now you get this: 

<img width="1485" alt="Screenshot 2023-11-05 at 1 49 33 PM" src="https://github.com/arch-kiosk/arch-kiosk-office/assets/67970402/d90948ac-042c-4c0c-bac4-c97746e32439">

**Comment by luizaogs** [comment] 2023-11-05 21:50
Also happens if I just search for LA and go from there, instead of first running a query.

**Comment by luizaogs** [comment] 2023-11-05 21:51
Same thing happens if you click on a collected material record in LA and follow the steps above. So this is the case for both context and collected material windows.

**Comment by urapadmin** [comment] 2023-11-06 00:35
might be also a duplicate of #2330

**Closed** 2023-11-08 23:51 UTC
Labels: 🐞 bug, kiosk
